package unsa.elb_moi.compiler;

public enum TokenType {
    INTEGER, DOUBLE, STRING, BOOLEAN, NULL,
    IDENTIFIER,
    CLASS, PUBLIC, PRIVATE, PROTECTED, STATIC, FINAL, ABSTRACT,
    VOID, INT, BOOLEAN_T, DOUBLE_T, LONG_T, CHAR_T, STRING_T,
    IF, ELSE, WHILE, FOR, RETURN, NEW, THIS, SUPER,
    TRUE, FALSE,
    IMPORT, PACKAGE,
    PLUS, MINUS, STAR, SLASH, PERCENT,
    EQ, EQ_EQ, BANG, BANG_EQ,
    LT, GT, LT_EQ, GT_EQ,
    AMP_AMP, PIPE_PIPE,
    PLUS_PLUS, MINUS_MINUS,
    PLUS_EQ, MINUS_EQ, STAR_EQ, SLASH_EQ,
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    SEMICOLON, COMMA, DOT,
    EOF, ERROR
}
