package unsa.elb_moi.compiler;

public enum TokenType {
    ENTERO, DOBLE, BOOLEANO, CADENA, NULO,
    IDENTIFICADOR,
    CLASE, PUBLICO, PRIVADO, PROTEGIDO, ESTATICO, FINAL, ABSTRACTO,
    FUNCION,
    VACIO,
    SI, SINO, MIENTRAS, PARA, RETORNAR,
    VERDADERO, FALSO,
    MAS, MENOS, MULT, DIV, MOD,
    IGUAL, IGUAL_IGUAL, DIF, DIF_IGUAL,
    MENOR, MAYOR, MENOR_IGUAL, MAYOR_IGUAL,
    Y_LOGICO, O_LOGICO,
    MAS_MAS, MENOS_MENOS,
    MAS_IGUAL, MENOS_IGUAL, MULT_IGUAL, DIV_IGUAL,
    PARENTESIS_IZQ, PARENTESIS_DER,
    LLAVE_IZQ, LLAVE_DER, CORCH_IZQ, CORCH_DER,
    PUNTO_COMA, COMA, PUNTO,
    EOF, ERROR
}